DROP TABLE IF EXISTS BOTTLES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE BOTTLES(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   BRAND           TEXT    NOT NULL,
   PRICE         INTEGER  NOT NULL,
   VOLUME         INTEGER   NOT NULL,
   COUNT          INTEGER   NOT NULL
);

INSERT INTO BOTTLES (BRAND, PRICE, VOLUME, COUNT)
VALUES ('Desperados', 410, 33, 5);

INSERT INTO BOTTLES (BRAND, PRICE, VOLUME, COUNT)
VALUES ('Guillotine', 590, 33, 8);

CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY   AUTOINCREMENT,
    USERNAME           TEXT    NOT NULL,
    PASSWORD        TEXT    NOT NULL,
    TYPE            TEXT    NOT NULL
);

INSERT INTO USERS (USERNAME, PASSWORD, TYPE)
VALUES ('admin', 'admin123', 'admin');

INSERT INTO USERS (USERNAME, PASSWORD, TYPE)
VALUES ('not_admin', 'not_admin123', 'visitor');
